services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: back-app
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ../src:/var/www:ro
    command: uvicorn public.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/front/Dockerfile
    container_name: front-app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    working_dir: /var/www
    depends_on:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: back-nginx
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: